name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install flake8
          pip install -r requirements.txt

      - name: Ejecutar flake8
        run: flake8 .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Ejecutar pruebas unitarias
        run: pytest app/tests/

  package:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Crear artefacto ZIP
        run: |
          zip -r flask_app.zip . -x '*.git*'

      - name: Guardar artefacto
        uses: actions/upload-artifact@v3
        with:
          name: flask_app
          path: flask_app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v3
        with:
          name: flask_app